### ISSUE TITLE
Too many `# pragma: no cover`

### ISSUE THREAD

**Issue by malmans2** [MaceKuailv/seaduck#10]
In my opinion there are too many `# pragma: no cover`.
Don't try to have 100% coverage, but focus on writing useful tests.

The coverage report should be a tool for yourself, too many pragma no cover is kinda cheating.
I recommend to remove all of them. If the coverage gets very low, let's think about why is so low and let's plan how we can improve it.

Side note: I see you switched `COV_REPORT` from `html` to `term-missing`. That's OK, I just want to make sure you know how to read the html report.
If you use `COV_REPORT := html`, then you can easily visualise the coverage of your tests.
```
open htmlcov/index.html
```
(I use open on mac, I think it's `xdg-open` on linux. Alternatively, you can use your favourite browser, such as `firefox htmlcov/index.html`)

**Comment by MaceKuailv** [comment]
I put some more thought about it. I think you are right. I should remove all of them. I think I sort of miss the point of testing when I was writing the tests in a frenzy. 

I am pretty happy with the actual coverage.
