### ISSUE TITLE
Generate zenodo archive

### ISSUE THREAD

**Issue by pnsaevik** [MaceKuailv/seaduck#101]
JOSS prequires that the software is uploaded as a Zenodo archive as a part of the acceptance process. You may want to prepare this archive in anticipation of acceptance. You can wait until version 1.0.0 for uploading to zenodo, but you might as well do it now to check that everything works as expected (and re-upload the final version).

Zenodo looks for a [citation file](https://zenodo.org/records/5171937) in the repo. If the citation file is not present, you will have to add some metadata manually.

This issue is a part of a JOSS review at https://github.com/openjournals/joss-reviews/issues/5967

**Comment by MaceKuailv** [comment]
I have uploaded it here (https://zenodo.org/records/10183124). 

Does it looks good to you?

**Comment by ThomasHaine** [comment]
looks good to me except there's a typo in the title

Sent via the Samsung Galaxy S21 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MaceKuailv** [comment]
Good catch. Fixed.

**Comment by MaceKuailv** [comment]
I am going to close this as done
