### ISSUE TITLE
Clarification about the content of the paper.md

### ISSUE THREAD

**Issue by syedhamidali** [MaceKuailv/seaduck#105]
Are you sure about the word "shear" volume in the paper's opening paragraph?
Consider revising the word 'shear' to 'sheer' in this context. The term 'sheer' is more appropriate when referring to the vast or complete extent of something, like the volume of the Earth's oceans. 'Shear' typically relates to a force causing parts of a material to slide past one another, which doesn't seem to align with the intended meaning here.

This issue is a part of the JOSS review at https://github.com/openjournals/joss-reviews/issues/5967

**Comment by MaceKuailv** [comment]
Thank you. This is a little embarrassing. The changes has been pushed into #99

**Comment by syedhamidali** [comment]
@MaceKuailv, I recommend ensuring consistency in the language style used throughout the text. For instance, if you're adopting American English, certain words will need to be updated to reflect this choice - for example, changing 'behaviour' to 'behavior'. Maintaining this consistency is important for the coherence and professionalism of the document.

**Comment by MaceKuailv** [comment]
Thanks. I have done some additional proofread in the PR. 

I apologize on behalf of my advisor @ThomasHaine for being British. :smile:

**Comment by syedhamidali** [comment]
Thanks for the proofreading! And no worries about @ThomasHaine, the British charm is always welcome 😊

**Comment by MaceKuailv** [comment]
closed with PR #99
