### ISSUE TITLE
Think carefully about `eval` and global variables

### ISSUE THREAD

**Issue by malmans2** [MaceKuailv/seaduck#16]
You should avoid using `eval` and global variables as much as possible.
You used `eval` in many tests, I removed it in some of them to show you some alternative. I suggest to go through the code and try to get rid of those.
For example, are you sure you need it here?
https://github.com/MaceKuailv/seaduck/blob/1c8c5ba918fe308d6789ddf07f2748e9527ba857/seaduck/smart_read.py#L73

Global variables are also something you should use very carefully! You should only use globals for things like constants, and always use `ALL_CAPS` name for the variables.
I don't follow exactly what you are doing here:
https://github.com/MaceKuailv/seaduck/blob/1c8c5ba918fe308d6789ddf07f2748e9527ba857/seaduck/kernel_weight.py#L593-L620
A function that access and modifies a global variables is quite dangerous. Why do you need it? Is it some sort of caching?

**Comment by MaceKuailv** [comment]
The first one is probably not necessary. 

I had a global dictionary of the weight functions that can be compiled. So that they don't have to be compiled multiple times. It helps the performance a bit (~10 second for every function already compiled).  I am slightly worried about it as well when I was writing it this way. But I have make sure only one function append and lookup from it, and no function delete things from it. I guess this might be OK?

**Comment by malmans2** [comment]
Yes, that's caching. I think you can use python's decorators `cache` or `lru_cache`: https://docs.python.org/3/library/functools.html

**Comment by MaceKuailv** [comment]
Yeah, I saw you using it for get_dataset. My first input is a numpy array which is not hashable by itself. Will that still work?

**Comment by MaceKuailv** [comment]
Ahhh, I should learn those things myself. never mind

**Comment by malmans2** [comment]
Idea:

```python
@cache
def cached_get_func(kernel_tuple, kernel_shape, *args, **kwargs):
    kernel = np.reshape(kernel_tuple, kernel_shape)
    ...
    
def get_func(kernel, *args, **kwargs):
    return cached_get_func(tuple(kernel.flatten()), kernel.shape, *args, **kwargs)
```

**Comment by MaceKuailv** [comment]
Resolved with PR https://github.com/MaceKuailv/seaduck/pull/38
