### ISSUE TITLE
Use assert in test functions

### ISSUE THREAD

**Issue by malmans2** [MaceKuailv/seaduck#17]
There are many `test_functions` that don't use assert.

That means that you are testing that the code doesn't crash, but you are not actually testing the results.
Try to rethink some of the tests so that you always know exactly what to expect.

> This is MaceKuailv adding a todo list.
- [x] assert after finding indices the location is the same. 
- [x] assert interpolation results. 
- [x] break down the `analytical_step` and use assert on each part of it.

**Comment by MaceKuailv** [comment]
Yes, I am actually actively working on that.
