### ISSUE TITLE
Add bots

### ISSUE THREAD

**Issue by malmans2** [MaceKuailv/seaduck#19]
There's a couple of very useful bots you should consider activating in this repo:

- https://pre-commit.ci/
- https://docs.codecov.com/docs/team-bot

If you activate the first one, we can just get rid of the GH action that is currently running pre-commit hooks.

**Comment by MaceKuailv** [comment]
I cut and paste the default bot into pre-commit.ci in PR #30, because when I was doing the testing I had so much trouble remembering to make qa. 

I will start working on the codecov bot tonight. My impression is that it does not require changing anything in the repo.

**Comment by malmans2** [comment]
For pre-commit ci you don't have to do anything in this repo. You just have to activate it here https://pre-commit.ci/
There's a few CI options that you can add in our `.pre-commit.yml`, but they're entirely optional.
Once it's done and the bot starts making PRs, you can remove the pre-commit action in `on-push.yml`.

BTW, if you always forget about qa, `pre-commit` is exactly what you are looking for!
In the seaduck conda env you are using on you machine, do this:
```
pre-commit install
```
It will run pre-commit every time you make `git commit` (actually, it will prevent you from committing until the code is in good shape).

**Comment by MaceKuailv** [comment]
Both bots are set up

**Comment by MaceKuailv** [comment]
I would like to keep the pre-commit hook in on-push, because it takes only a few seconds. 

> If you activate the first one, we can just get rid of the GH action that is currently running pre-commit hooks.
