### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by malmans2** [MaceKuailv/seaduck#20]
In order to trigger PyPI releases, you need to set up the trusted publisher workflow on PyPI: https://docs.pypi.org/trusted-publishers/

**Comment by MaceKuailv** [comment]
I would need a .yml file for some workflow stuff. I am not entirely sure what they are asking for.

**Comment by malmans2** [comment]
PyPI just asks the name of the `.yml` with the publishing action, and the name of the environment.
It should be `pypi.yml` and `pypi`, respectively.
See: https://github.com/MaceKuailv/seaduck/blob/c43649dc66c6914a9aaa980fd1368588691c80d2/.github/workflows/pypi.yml#L16

**Comment by MaceKuailv** [comment]
I just added a trusted publisher. I am not sure about the environment name. What I used is the header of `pypi.yml` : `Publish to PyPI`. 

@malmans2 Is this going to be triggered in the next PR? Otherwise, how should I test it?

**Comment by malmans2** [comment]
> I just added a trusted publisher. I am not sure about the environment name. What I used is the header of `pypi.yml` : `Publish to PyPI`.

No, the environment name is `pypi`: https://github.com/MaceKuailv/seaduck/blob/9205d40f0741ad40d91ad79d915d73439be36830/.github/workflows/pypi.yml#L15-L16

> @malmans2 Is this going to be triggered in the next PR? Otherwise, how should I test it?

No, the PyPI publishing is only triggered when you make a release: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

**Comment by malmans2** [comment]
@MaceKuailv First attempt failed...
Delete the GH release you just made, and try again.
This time though add a `v` in from of the release (I think this is what GH suggests).
So release and tag should be `vX.X.X`

**Comment by MaceKuailv** [comment]
Didn't saw that message. I added a token to pypi and this repo when I made the release following https://imsadra.me/automate-your-python-package-release-w-github-actions. I am not sure whether I should have done that? The error message was

* `invalid-pending-publisher`: valid token, but project already exists

I will try adding v first.

**Comment by malmans2** [comment]
Do the `v` thing as it's good practice.
We don't need a token in this repo, this probably explains the error.
PyPI only needs the trusted publishers, no need to create a token.

The link you share is out of data. It's the same we did in OceanSpy, deprecating token in favour of trusted publishers.
See: https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by MaceKuailv** [comment]
The latest merge checks got triggered everytime I try to publish the release. Is that normal?
![image](https://github.com/MaceKuailv/seaduck/assets/52629492/a2a55671-503d-4131-bea0-0cd919bab7d2)
Is that what this part do?
![image](https://github.com/MaceKuailv/seaduck/assets/52629492/42d88ade-b08b-44ea-9cbd-b354e1090d1d)

**Comment by MaceKuailv** [comment]
Terrific, It is successfully released.
