### ISSUE TITLE
Publish the documentation

### ISSUE THREAD

**Issue by malmans2** [MaceKuailv/seaduck#21]
Looks quite easy: https://jupyterbook.org/en/stable/start/publish.html#publish-your-book-online-with-github-pages

**Comment by MaceKuailv** [comment]
It could also be published on read the docs. It requires a little bit more work though. (I slightly prefer the the readthedocs url to the pages one, but prefer the jupyter book theme.)

**Comment by MaceKuailv** [comment]
It is now published on github pages. Very easy to do.

**Comment by MaceKuailv** [comment]
It can be found here: https://macekuailv.github.io/seaduck/intro.html

**Comment by malmans2** [comment]
I would edit the About section of GitHub (main page of sea duck), you can add a website.
I would add the link to the documentation there, easier to find.
