### ISSUE TITLE
Remove print from code

### ISSUE THREAD

**Issue by malmans2** [MaceKuailv/seaduck#27]
I suggest to remove all `print("bla bla bla")` from the code (I'm talking about python files, prints can be OK in jupyter).

Use [warnings](https://docs.python.org/3/library/warnings.html) if the print is a warning that gets triggered just if certain conditions are met.
Use the appropriate warning type (e.g., UserWarning, DeprecationWarning, ...) so users can silence or catch them if they need to.

Use [logging](https://docs.python.org/3/library/logging.html) if you want to add debugging statements. No need to use if statements in the code (e.g., no need `if debug: ...`, it's the user that decides the logging level depending on their needs. You just have to decide the appropriate level of the messages ("DEBUG", "INFO", ...)

**Comment by MaceKuailv** [comment]
After resolving this, issue #26 is no longer relavant

**Comment by malmans2** [comment]
Sounds good. Good practice is to use model level loggers:
```python
import loggin
import xarray as xr
...

LOGGER = logging.getLogger(__name__)

def seaduck_function(a, b, c):
    LOGGER.info("bla bla bla")
    LOGGER.debug("bla bla bla")
```

BTW, it's the 3rd time I realize that `D` and `F` are dangerously close to each other on the keyboard.
So just be aware that if I ever write `"seaduck".replace("d", "f")`, it's a typo!!!!

**Comment by MaceKuailv** [comment]
Just did
