### ISSUE TITLE
Don't use `elif/else` with things like `return` or `raise`

### ISSUE THREAD

**Issue by malmans2** [MaceKuailv/seaduck#48]
Just another small best practice tip.

Don't use `elif/else` with things like `return` or `raise`. It will make the code more readable, and it's easier to understand what's going on.

Here is a simple example:
```python
if math.sqrt(num) % 2 == 0:
    return True
elif (math.sqrt(num) + 1) % 2 == 0:
    return True
else:
    return False
```
becomes
```python
if math.sqrt(num) % 2 == 0:
    return True
if (math.sqrt(num) + 1) % 2 == 0:
    return True
return False
```

**Comment by malmans2** [comment]
I.e., don't use `elif/else` when you exit in the previous if

**Comment by MaceKuailv** [comment]
`pylint` caught this as well...

However, I am not very convinced it makes it easier to read. For example, 
```
if scenario_a:
    several_line_of_code
    return result
# else: / if not scenario_a:
another_block_of_code
return result
```
How the second return is related to scenario_a is obscured by potentially two large chunks of code. If it is not done in this way, one can just trace back the indented block and figure out the if structure in no time. 

For the machine, these things are also more or less the same, right?

People has discussed this issue from time to time, although I couldn't find any new ones. Here are two:
https://www.reddit.com/r/learnpython/comments/9gh4al/another_if_elif_return_question/
https://stackoverflow.com/questions/22782785/when-to-use-if-vs-elif-in-python

**Comment by malmans2** [comment]
Up to you.
If you think that it actually makes the code less readable, you don't have to necessarily follow common practices.

My 2 cents: I don't find your example particularly convincing.
You shouldn't have several lines of code in an `if` block, but you should use a function with a self describing name:
```python
if scenario_a:
    return modify_result_for_scenario_a(result, *args, **kwargs)
return result
```

**Comment by MaceKuailv** [comment]
I think there is an alternative to this, that is better than both of them and not against the common practice
```
if A:
    to_return = some_expression_a()
elif B:
    to_return = second_expression()
else C:
    to_return  = some_other_expression()
return to_return 
```
This will make sure there is only one exit point in a function. 

What do you think? @malmans2

**Comment by malmans2** [comment]
Even in this case I would have written it differently. 
As the variable name suggests, If I know that the variable is ready to be returned, why would I wait?
And if another person reads the code, and they are only interested/debugging case A, why should they care about whatever happens after?

```python
if A:
    return some_expression_a()
if B:
    return second_expression()
...
```

But again, these kind of things are not strict rules, and maybe other people do it differently. Do whatever you think it's the best, you can always change later if you change your mind.

**Comment by MaceKuailv** [comment]
Thank you! I can see why to_return can be a bad idea. 

I have to admit that I have not develop a "taste" for code. Although I still prefer elif at this moment, I guess it is pretty likely for me to change my mind in the future.
Let's keep this issue open. I will learn some more and revisit this.
