### ISSUE TITLE
smart read

### ISSUE THREAD

**Issue by malmans2** [MaceKuailv/seaduck#49]
Hi,

I'm surprised you had to code [smart_read](https://github.com/MaceKuailv/seaduck/blob/80b824865a84d6fed6a8fbeaa5502996a46c2498/seaduck/smart_read.py#LL7C9-L7C9) to have good performance.
I have a few tips, but before I would like to explore `xarray/dask/numpy` optimisations.

Do you have a good MRE where `smart_read` makes the difference and that I can use to benchmark?

**Comment by malmans2** [comment]
yup, sciserver works

**Comment by MaceKuailv** [comment]
Here is an example
```
import oceanspy as ospy
import numpy as np
import xarray as xr

od = ospy.open_oceandataset.from_catalog('HYCOM')
size = 100000
iy = np.random.randint(1251, size = size)
ix = np.random.randint(701, size = size)
it = np.random.randint(5, size = size)
# this is randomly seeded in two chunks. 

# %%time this block runs for about 130ms
array = np.array(od._ds.Eta.isel(time = slice(0,5)))
res = array[it,iy,ix]

# %%time this run a little less than 2 seconds
xrind = tuple(xr.DataArray(dim, dims=["new"]) for dim in (it,iy,ix))
res = np.array(od._ds.Eta[xrind])
```
The difference here is actually not very large, but if you do the same operation repeatedly, it is going to be significant. 
I remember from a year ago there are cases on ECCO that the former is hundreds of times faster than the latter.

**Comment by MaceKuailv** [comment]
I agree this is an ad hoc thing, and the majority of the function is not very frequently called. 

When I first started developing this, I remember reading one single entry from ECCO using xarray takes 2 seconds. This is either because the xarray code has improved, or because we were using netcdf at that point.

**Comment by malmans2** [comment]
```python
import oceanspy as ospy
import numpy as np
import xarray as xr

od = ospy.open_oceandataset.from_catalog("HYCOM")
da = od._ds.Eta.isel(time=slice(0, 5))

size = 100000
iy = np.random.randint(1251, size=size)
ix = np.random.randint(701, size=size)
it = np.random.randint(5, size=size)

indexers = {dim: xr.DataArray(indexes) for dim, indexes in zip(da.dims, (it, iy, ix))}
```

    Opening HYCOM.
    High-resolution grid of the (1/25 deg) numerical simulation covering the California Coast using the HyCOM model. The original grid has 41 (isopycnal) layers but these files were interpolated to 101 vertical levels.
    See also:
     * Sample (test) files



```python
_ = da.values  # make sure there's no caching
```


```python
%%timeit
da.values[it, iy, ix]
```

    68.7 ms ± 5.97 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)



```python
%%timeit
da.isel(indexers).values
```

    1.37 s ± 102 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)



```python
%%timeit
da.data.vindex[it, iy, ix]
```

    954 ms ± 54.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)



```python

```

**Comment by malmans2** [comment]
Here is the same benchmark removing the slicing of da performed in the previous one.
Data is big now, so I had to remove numpy benchmark because it blows up.
However, both xarray and pure dask works with no problem, and they take about the same time as before:

```python
import oceanspy as ospy
import numpy as np
import xarray as xr

od = ospy.open_oceandataset.from_catalog("HYCOM")
da = od._ds.Eta

size = 100000
iy = np.random.randint(1251, size=size)
ix = np.random.randint(701, size=size)
it = np.random.randint(5, size=size)

indexers = {dim: xr.DataArray(indexes) for dim, indexes in zip(da.dims, (it, iy, ix))}
```

    Opening HYCOM.
    High-resolution grid of the (1/25 deg) numerical simulation covering the California Coast using the HyCOM model. The original grid has 41 (isopycnal) layers but these files were interpolated to 101 vertical levels.
    See also:
     * Sample (test) files



```python
%%timeit
da.isel(indexers).values
```

    1.47 s ± 103 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)



```python
%%timeit
da.data.vindex[it, iy, ix].compute()
```

    1.58 s ± 118 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by MaceKuailv** [comment]
For my purposes, there tend to be some locality of the data. For example, the velocities I read is going to be at the same time. So the indexes I am interested in tends to be on a few chunks. The problem for using values is that it may not be very easy to figure out how to slice. For example, for LLC 4320 data, each face is a chunk, but I want to read only from face 2 and 10 but not 3,4,5,6...

Since most of the time is spend reading the data, figuring out which chunks to read is not too time consuming. If I only need to read a couple of chunks, it is faster than xarray (at least was). 

Again, I am not claiming this is anywhere near the best way to do it. I isolate the function so much is precisely because I would like to improve it in the future.

**Comment by malmans2** [comment]
ahhh, now I understand the goal of this function.
Indeed it's much faster using the example above! I'll see if we can implement something similar in `xarray`.
```python
%%timeit
smart_read(da, (it, iy, ix))
```

    281 ms ± 12.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by MaceKuailv** [comment]
Got quite some improvement here #51. We might revisit some day.

**Comment by malmans2** [comment]
Ah, you merged quick. Final comments:
1. docstring is too long and still a little vague. I'd use a single sentence and get rid of all the useless stuff (e.g., if you want to say that you'll change it, say what needs to be improved. Otherwise, it's just adding noise and we have more docstring than code).
2. TODO comment. We had a discussion about it, looks like you know what's going on, change the comment with something more meaningful, like `# TODO: we need this because ...`
3. Not 100% sure, but I think it's better to add `dask[array]` in pyproject rather than `dask`
4. Why did you change the dask switch from 100 to 10?.

**Comment by MaceKuailv** [comment]
>     1. docstring is too long and still a little vague. I'd use a single sentence and get rid of all the useless stuff (e.g., if you want to say that you'll change it, say what needs to be improved. Otherwise, it's just adding noise and we have more docstring than code).
OK, I will change that.
>     2. TODO comment. We had a discussion about it, looks like you know what's going on, change the comment with something more meaningful, like `# TODO: we need this because ...`
I don't think there is anything that needs to be done about it here. But I will change that. 
>     3. Not 100% sure, but I think it's better to add `dask[array]` in pyproject rather than `dask`
I didn't know you could just add dask.array as an dependency. I will try that.
>     4. Why did you change the dask switch from 100 to 10?.
Based on some rough bench marking, for a typical number of particles, 10^4- 10^7 (I tested 10^5) this is a good criterion to switch.
