### ISSUE TITLE
Support for time formats

### ISSUE THREAD

**Issue by ThomasHaine** [MaceKuailv/seaduck#59]
`seaduck` should support the time formats used in SciServer datasets. E.g., `ECCO` times are strings like this: '1992-01-16T12:00:00.000000000'. Reading this with `sd.utils.convert_time` errors:

<img width="951" alt="image" src="https://github.com/MaceKuailv/seaduck/assets/44037162/8b1b2fb2-d816-4d0c-abee-2baa6360eb75">

**Comment by ThomasHaine** [comment]
Sorry!  My Python coding error. This works fine:

<img width="365" alt="image" src="https://github.com/MaceKuailv/seaduck/assets/44037162/06261b33-3815-4698-8163-e42c5e1ea79d">

**Comment by MaceKuailv** [comment]
Yeah, it should support any string with the [datetime64 format](https://numpy.org/doc/stable/reference/arrays.datetime.html). If some how it doesn't work, you could just pass in a np.datetime64 object rather than a string.
