### ISSUE TITLE
Tutorial errors are not captured by tests

### ISSUE THREAD

**Issue by pnsaevik** [MaceKuailv/seaduck#92]
I intentionally introduced an error to one of the tutorial files. The error shows up as a warning in the jupyter-book build log, but does not generate a nonzero exit value and is therefore not captured by the CI testing framework. It is important that tutorials are regularly tested, so that any changes to the API that breaks the examples are immediately reported to developers.

This issue is a part of a JOSS review at https://github.com/openjournals/joss-reviews/issues/5967

**Comment by MaceKuailv** [comment]
Yes! I wanted to have that a while ago, but didn't know how to achieve it. I will revisit it today.

**Comment by MaceKuailv** [comment]
Resolved with PR #95
