### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by pnsaevik** [MaceKuailv/seaduck#94]
In my opinion, a JOSS submission should be marked as `Development Status :: 5 - Production/Stable` on PyPI, and it's version number should not start with 0 (see also, e.g., https://martin-thoma.com/software-development-stages/). 

This package is already quite mature, so there is no reason it should not be marked as "Stable", even with the issues I previously raised on GitHub. With one exception: It should be clear to the user which part of the API is considered stable, and which is open to change. At the very least, examples in the tutorials should have "frozen syntax" and should not be changed except at infrequent major version upgrades.

Before bumping up the release to version 1.0.0, I suggest you do the following:

1. Fix minor issues already raised
2. Clearly state which part of the API is fixed, either summarized on the API Reference front page or individually for each exposed function.
3. If you are unhappy with any part of the public API, now is the time to fix it. Do an internal review among developers and internal users:
3.1. Are the variable/class/function/parameter names intuitive?
3.2. Is the naming scheme consistent? 
3.3. Are we happy with the module/class organization? Should something be moved?
3.4. Remember that parameter names, their ordering, and possible default values are part of the public API. Go through each function and make changes if necessary, before declaring the function as a part of the public "frozen" API.

This issue is a part of a JOSS review at https://github.com/openjournals/joss-reviews/issues/5967

**Comment by MaceKuailv** [comment]
Thank you! I was not aware of the convention of releases. This is very helpful. I think I will bump it up to 1.0.0 when both of you are happy with it. 

I don't think there is going to be a lot of changes to the syntax or keyword arguments on functions and classes used in the tutorial examples. Before submitting this paper, we spend a lot of time discussing pretty much exactly the third item and already made a lot of changes. For example, PR #58. 

I am not entirely sure what you mean by labeling the part of API that is fixed. Do you have an example on how other people did that? Thanks!

**Comment by MaceKuailv** [comment]
OK, I think that's very doable and useful. I will make it clear in the table of content. I will also look into the public files and identify the non-public functions and underscore them.

**Comment by MaceKuailv** [comment]
The final changes I made in PR #95 implemented that. You can take a look after the website finishes building.

**Comment by pnsaevik** [comment]
Great, the change to the documentation resolves the issue. There is still some potensial for polishing the documentation, but this is "further work".

If you want a small sample ROMS dataset for extending your package, take a look at https://github.com/pnsaevik/ladim_plugins/blob/master/ladim_plugins/chemicals/forcing.nc. It's an exercept from a fjord model in southern Norway.
